### ISSUE TITLE
[FR] FolderNotes 插件兼容

### ISSUE THREAD

**Issue by Moyf** [xhuajin/obsidian-file-preview#10]
使用这个插件的时候发现有时候会有一个很窄的 Hover 条：
![image](https://github.com/user-attachments/assets/68f40db9-f29b-4f56-926b-cdba570b33a3)

自己倒是研究出来一个 css 代码片段可以修复这个问题：
```css

/* 和 FolderNotes 兼容，不显示特别窄的那个框 */
.tree-item.nav-file:has(.is-folder-note ):hover{
    background-color: unset;
    border-radius: unset;
    box-shadow: unset;
}

```

另外发现有时候会有一个空档，也是 FolderNotes 引起的，这个不知道有没有办法避免？
![image](https://github.com/user-attachments/assets/ec77ed4b-0022-4ab1-b4f4-e9dd1ec8df31)

___

FolderNotes 插件：
https://github.com/LostPaul/obsidian-folder-notes
