### ISSUE TITLE
可以增加一个调整预览字体的设置吗，需要小一点灰暗一点，才能更好区分文件名和预览

### ISSUE THREAD

**Issue by Qloulia** [xhuajin/obsidian-file-preview#11]
![1726142584832.jpg](https://github.com/user-attachments/assets/62140bd2-ff13-48af-8490-53bc6098d7d6)

非常喜欢你的插件！我很需要能在obsidian看到预览！图片是纯纯写作的预览，清晰明了，还有时间元数据，如果能在插件中实现就太好啦！非常感谢！

**Comment by xhuajin** [comment]
时间元数据的功能在 1.1.0 添加了。 [release-1.1.0](https://github.com/xhuajin/obsidian-file-preview/releases/tag/1.1.0). 预览字体可以通过添加 css 修改，例如

```css
.file-preview-nav .tree-item-self.nav-file-title.fp-nav-file .nav-file-details,
.file-preview-nav .tree-item-self.nav-file-title.fp-nav-file .nav-file-properties {
  color: gray;
  font-size: 10px;
  font-weight: 400;
}
```

可以根据你的需要修改字体颜色、字体大小和字体粗细。

**Comment by Qloulia** [comment]
我试了一下这个css只改变了properties，预览内容本身还是没有变化😭我不太懂编程，这个预览内容应该怎么在css中描述啊？

**Comment by xhuajin** [comment]
那你试下下面这个，这次应该可以。第一块为预览内容，第二块为元数据内容。

```css
.file-preview-nav
  .tree-item-self.nav-file-title.fp-nav-file
  .tree-item-inner.nav-file-details {
  color: gray;
  font-size: 10px;
  font-weight: 300;
}

.file-preview-nav
  .tree-item-self.nav-file-title.fp-nav-file
  .nav-file-properties {
  color: gray;
  font-size: 10px;
  font-weight: 300;
}
```

**Comment by Qloulia** [comment]
太感谢啦！完美！

**Comment by Qloulia** [comment]
好像这个css对后面更新的几个版本都不起作用了！麻烦作者大大再帮忙看下！谢谢！

**Comment by xhuajin** [comment]
新版本修改了一些css类，确实之前的不起作用了，你可以用下面这个，然后自行修改里面的 color / font-* 等属性

```css
.file-preview-nav:not(.hide-preview-contents)[data-type="file-explorer"]
  .tree-item-self.nav-file-title
  .tree-item-inner.nav-file-details {
  color: red;
  font-size: 10px;
  font-weight: 300;
}

.file-preview-nav:not(.hide-preview-contents)[data-type="file-explorer"]
  .tree-item-self.nav-file-title
  .nav-file-properties {
  color: green;
  font-size: 10px;
  font-weight: 300;
}
```
